openapi: 3.0.0
info:
  title: Backend for Docker containers ping info service
  version: 0.1.0
servers:
- url: http://backend
  description: Backend
paths:
  /pings:
    get:
      summary: Получить информацию о пингах
      parameters:
      - name: container_ip
        in: query
        description: "IP контейнера, для которого выдавать список пингов"
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: 127.0.0.1
      - name: oldest_first
        in: query
        description: Сортировать начиная со старых записей
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: success
        in: query
        description: Возвращать только успешные или неудавшиеся записи
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: limit
        in: query
        description: Максимальное количество выдаваемых результатов
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
      - name: offset
        in: query
        description: "Количество результатов, которое необходимо пропустить"
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PingInfo'
                x-content-type: application/json
        "400":
          description: Ошибка на стороне пользователя
        "500":
          description: Ошибка на стороне сервера
    put:
      summary: Загрузить информацию о пингах
      requestBody:
        description: Список результатов пинга
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PingInfo'
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Ошибка на стороне пользователя
        "500":
          description: Ошибка на стороне сервера
  /pings/aggregate:
    get:
      summary: Получить информацию о контейнерах и их последнем пинге
      parameters:
      - name: oldest_first
        in: query
        description: Сортировать начиная со старых записей
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: limit
        in: query
        description: Максимальное количество выдаваемых результатов
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
      - name: offset
        in: query
        description: "Количество результатов, которое необходимо пропустить"
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContainerInfo'
                x-content-type: application/json
        "400":
          description: Ошибка на стороне пользователя
        "500":
          description: Ошибка на стороне сервера
components:
  schemas:
    ContainerInfo:
      required:
      - ip
      type: object
      properties:
        ip:
          type: string
        last_ping:
          type: string
          format: date-time
        last_success:
          type: string
          format: date-time
      example:
        ip: 127.0.0.1
        last_ping: 2025-02-08T17:17:51.873Z
        last_success: 2025-02-08T17:17:51.873Z
    PingInfo:
      type: object
      properties:
        container_ip:
          type: string
        timestamp:
          type: string
          format: date-time
        success:
          type: boolean
      example:
        ip: 127.0.0.1
        timestamp: 2025-02-08T17:17:51.873Z
        success: true
  parameters:
    ContainerIP:
      name: container_ip
      in: query
      description: "IP контейнера, для которого выдавать список пингов"
      required: false
      style: form
      explode: true
      schema:
        type: string
      example: 127.0.0.1
    Limit:
      name: limit
      in: query
      description: Максимальное количество выдаваемых результатов
      required: false
      style: form
      explode: true
      schema:
        minimum: 0
        type: integer
    Offset:
      name: offset
      in: query
      description: "Количество результатов, которое необходимо пропустить"
      required: false
      style: form
      explode: true
      schema:
        minimum: 0
        type: integer
    OldestFirst:
      name: oldest_first
      in: query
      description: Сортировать начиная со старых записей
      required: false
      style: form
      explode: true
      schema:
        type: boolean
    FilterSuccess:
      name: success
      in: query
      description: Возвращать только успешные или неудавшиеся записи
      required: false
      style: form
      explode: true
      schema:
        type: boolean
