/*
 * Backend for Docker containers ping info service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ContainerInfo struct {
	Ip string `json:"ip"`
	LastPing time.Time `json:"last_ping,omitempty"`
	LastSuccess time.Time `json:"last_success,omitempty"`
}
