/*
 * Backend for Docker containers ping info service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PingInfo struct {
	ContainerIp string `json:"container_ip,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	Success bool `json:"success,omitempty"`
}
